version: "2"
linters:
  default: none
  enable:
    - gocritic
  settings:
    gocritic:
      disable-all: true
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          failOn: all
          rules: gorules/format.go
