# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: prl

report_sizes: true

env:
  - CGO_ENABLED=0

builds:
  - binary: prl
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{ .Version }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
