# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: prl

report_sizes: true

env:
  - CGO_ENABLED=0

builds:
  - binary: prl
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w

checksum:
  name_template: checksums.txt
  algorithm: sha256

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz

brews:
  - repository:
      owner: gechr
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/gechr/prl
    description: "Search, filter, display, and act on GitHub pull requests"
    install: |
      bin.install "prl"
    test: |
      assert_match "prl", shell_output("#{bin}/prl --help")

changelog:
  filters:
    exclude:
      - "^brew: "

release:
  footer: |-
    ## Installation

    ```shell
    brew install gechr/tap/prl
    ```
